### ISSUE TITLE
Bed Leveling Wizard

### ISSUE THREAD

**Issue by Karrad** [alephobjects/Cura#101]
Some customers have attempted to use Curas Bed Leveling Wizard when setting up their TAZ. The up and down movements are inverted. 

It may be best to modify it for our bed leveling procedure, or remove it all together as it has confused a couple of customers. (We never use it)

**Comment by kakaroto** [comment]
The bed leveling wizard was disabled for the TAZ, until 1.18.7 released caused an issue where it would not be disabled see issues #89
I only saw how it affected quickprint settings but missed that it also affects the bed leveling wizard option, which I later fixed in commit 62a98dc5e1db10d0ba0385fc62eda8691f84c42f while doing upstreaming of the 15.02 version.
