### ISSUE TITLE
Layer scroll bar overlaps the Viewer buttons when the Cura window is made smaller

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#18]
![scroll_bar_overlap](https://cloud.githubusercontent.com/assets/849151/4781884/aa1f21fc-5cc6-11e4-91a3-a3ed353adf27.png)

**Comment by kakaroto** [comment]
The layer scrollbar could be moved a few pixels towards the left when the view mode is expanded so it doesn't interfere with it, and then goes back to its original position when view mode is collapsed, or it could be moved a few pixels to the left permanently or it could be moved to the left side of the window instead of the right side. 
The suggestion I would go for would be to just make the layers scroll bar disappear when the view mode is expanded and reappear after a mode is selected. It's more simple and less confusing (items moving is not a great idea). 
So what do you suggest? Should I implement it that way ?

**Comment by Jnesselr** [comment]
Either way will cause a refresh. I have nothing against moving it, but we
have to make sure either way that the click events work correctly, even if
the bar isn't visible.

**Comment by kakaroto** [comment]
Reopening this issue since the upstream branch has a new 'layers' icon below the layers scrollbar which isn't hidden with the original fix.

**Comment by kakaroto** [comment]
Fixed now.
