### ISSUE TITLE
Language should use system language

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#29]

**Comment by kakaroto** [comment]
Default language is now set to 'AUTO' which will use the locale to determine the language until the language gets modified. I'm trying now to add an "Auto detect" option to the menu.

**Comment by kakaroto** [comment]
It's done, the thing that I don't like is that the language is not translated because the settings UI forces the profile variable to be the same as the choice in the menu, so we can't translate 'Autodetect' or the language names themselves without having the profile variable set to the translated value which wouldn't work so well 
Anyways, I'm closing this issue, if further work is needed for it, we can reopen it later.
Note: I didn't test it on windows though I expect it to work.
