### ISSUE TITLE
Pull in updates from Daid's Cura

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#40]

**Comment by kakaroto** [comment]
I've merged AO-build into the upstream branch then cherry-picked all the commits from daid/SteamEngine into it up to the 14.12 tag.

I've tagged it as lulzbot-14.12-rc1. It is missing the commits from master and production-phase1 branches which weren't merged yet into AO-build, and it's also missing the upstream commits for 15.01 development (since it's not stable, I wasn't sure if we wanted to pull those commits yet or not).
Note: After I cherry-picked everything (with some of my own commits in between when something wasn't working), I did a merge again against the daid/SteamEngine branch and re-resolved the conflicts, this way we actually have a merge (don't know if it affects anything vs. only cherry-picks).

I didn't tag it lulzbot-14.12 because I think it still needs the production-phase1 and master commits merged into it before we tag it as the 14.12 lulzbot edition release.
I'll be creating a new branch now for commits that we've done that should be sent upstream.

**Comment by kakaroto** [comment]
I merged the 15.02.1 tag from upstream into the upstream branch, fixing conflicts and adding back the new simple-setting system to allow overrides for the lulzbot and TAZ machines.
There's one issue though, the start.gcode/end.gcode stuff is not a profile option, it's an alteration profile, and daid's code checks for setting.isProfile() before applying the override, so the start/end gcodes were ignored. I've made the modifications to fix it but this causes the issue that if you overwrite full settings with the quick print settings from the mini, you will get the start.gcode modified on all the machines, not just for the machine.
It looks like an 'alteration setting' means that the setting applies to all machines. If we don't overwrite it though then people who want to tweak the quickprint settings in the full setting mode will not have the right start gcode.
Should I open a new issue to discuss this particular issue ?

**Comment by kakaroto** [comment]
Since upstream seems to have stopped supporting this version of Cura, separating bugfixes from lulzbot-related commited and creating a pull request is not worth the effort (as discussed with @nickthetait), so let's close this issue for now.
