### ISSUE TITLE
Cura is dumping large amounts of data into x-session

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#45]
This is only confirmed on Debian with xfce. It does not occur on Ubuntu with Unity or Gnome nor Debian with Gnome.

**Comment by kakaroto** [comment]
With all the recent commits, I believe this is fixed. Please confirm and close the issue.

**Comment by Jnesselr** [comment]
I'd still be concerned about all of the subprocess calls that pipe stdin
and stdout. There's also some generic print statements littered about the
code.

**Comment by kakaroto** [comment]
I don't think that's an issue, at least I didn't see any of that in the log that @reprapperMC sent me. The issue here isn't that there is output in the xsession file, but rather that it dumps large amounts of data into it (@reprapperMC talks about the file reaching 200GB after a few days of use). At least this should be fixed.
If you want, I could make a logging system and write everything to a file and have nothing appear in stdout, but I don't really see the point if it's not intensive.

**Comment by jebba** [comment]
FWIW, I haven't seen this error in a long time. I often run cura in a terminal, so it dumps the data there instead of ~/.xesssion-errors, but it is the same thing.

**Comment by kakaroto** [comment]
I'm closing this issue for now, if you notice there is still intensive data being printed, please reopen.
