### ISSUE TITLE
Auto sleep state kills print

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#46]
With the default OSX energy saver settings the serial connection is stopped and the printed killed when the sleep state occurs. This may occur in other OS but has not been reported.

**Comment by reprapperMC** [comment]
This looks good to go from my testing. Closing the issue, but we'll get more testing over the next few days.

**Comment by kakaroto** [comment]
I added support for linux but unfortunately I can't test because I can't even get my system to suspend on idle.
This uses the same method as Caffeine though https://launchpad.net/caffeine which I assume works.
Side effect is that the screensaver also gets disabled.
If someone else can test it and report if it works for them or not and if it's an acceptable solution, that would be great.
Thanks.

**Comment by reprapperMC** [comment]
Going to close this as it is confirmed to work on OSX and Windows. I haven't been able to make this occur on Linux even before the commit so I will make a separate issue for that.
