### ISSUE TITLE
Check sum errors appear in the Printrun UI terminal window

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#66]
At the start of a print checksum errors appear in the Printrun UI terminal. The prints do not appear to be affected but we have seen a number of questions in the user testing. Example terminal line:

Error: No Line Number with checksum, last line 67

**Comment by kakaroto** [comment]
We can't do that because not only would it make the code much more complex (therefore, more prone to bugs) and wouldn't work for resends due to the line-based nature of the communication protocol, but also, we don't know how many bytes Marlin has consumed so far... Marlin should be able to hold 4 commands at a time and then there will be 64 byes buffer on the serial interface, somehow it doesn't look like that's what happens, I have no idea why because it looks like it only consumes one command, and then when we send more data, the serial buffer becomes full.
Even if we send only 64 bytes at a time, we wouldn't know how many of those bytes were consumed so we wouldn't know when to send more.
The commit I did to lower the number of commands sent simultaneously fixes the issue though.
