### ISSUE TITLE
Bed Temperature value is off by a degree

### ISSUE THREAD

**Issue by imbondzai** [alephobjects/Cura#73]
the cura software is reading the value of the bed by a lower value than the printer (lulzbot taz4). example: print head value on taz is 225C, and the bed is 95C, cura reads the print head at 225C and the bed at 94C. since the taz reads the bed at 95, it holds the temp. cura waits (forever) for the bed to increase a degree before starting the print.

**Comment by kakaroto** [comment]
That's not actually how it works, the issue is that Marlin will round up the temperature value, so if it's 94.6C it will show 95C on the LCD.
Cura isn't the one waiting for the temperature to reach 95C either, it's the Marlin firmware itself as well which waits for it to reach 95C, all Cura does is tell Marlin to wait until it reached 95C and waits for Marlin to say it's done. 
Your issue for it taking a long time is caused by improper PID for the bed which causes it to slow down as it approaches the target temperature. You will get the exact same behavior if you print from SD card for example and not use Cura or Pronterface at all.
to fix your PID values, refer to this : https://www.lulzbot.com/support/fine-tune-your-marlin-pid-settings
or also : http://reprap.org/wiki/PID_Tuning

**Comment by imbondzai** [comment]
Hi Youness,

Thank you very much for your reply!

Don
