### ISSUE TITLE
Force simpleMode when switching between machines

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#8]
When switching between machines, some machines force advanced mode but do not resize the side panel. The panel either needs to be resized or force simpleMode for all machines by default.

**Comment by kakaroto** [comment]
I believe this issue is now fixed. The problem was that switching machines made it reload the left pane and if we were in simple mode, it would think it changed from normal to simple and will store the new size in the config, so if we then switch to advanced, the size was all wrong.
Now we properly tell the function whether or not the slice mode was changed, or if we just want to reload the left pane (when switching machines or after first run wizard) so it knows whether or not to save the size and to resize the left pane.
I also made it switch to simple mode automatically when a TAZ or Mini machine gets added.
